on:
  workflow_call:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  build-and-scan-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ secrets.DEPLOY_APPLI_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner (JSON)
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: ${{ secrets.DEPLOY_APPLI_NAME }}:${{ github.sha }}
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract CVE list from Trivy report
        run: |
          jq . trivy-results.json
          jq -r '.Results[].Vulnerabilities[].VulnerabilityID' trivy-results.json | sort | uniq > cve-list.txt
          cat cve-list.txt

      - name: Upload CVE list
        uses: actions/upload-artifact@v4
        with:
          name: cve-list
          path: cve-list.txt

      - name: Run Trivy vulnerability scanner (SARIF)
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: ${{ secrets.DEPLOY_APPLI_NAME }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-results.sarif
          category: trivy-container-scan

      - name: Check for critical vulnerabilities
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: ${{ secrets.DEPLOY_APPLI_NAME }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          trivyignores: .trivyignore